/// Flutter icons SignUpViewIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SignUpViewIcon
///      fonts:
///       - asset: fonts/SignUpViewIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SignUpViewIcon {
  SignUpViewIcon._();

  static const _kFontFam = 'SignUpViewIcon';
  static const String? _kFontPkg = null;

  static const IconData eyeslash = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
